"""initial schema: urls and clicks

Revision ID: 479def36828f
Revises: 
Create Date: 2026-08-01 19:36:15.438171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479def36828f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('original_url_hash', sa.String(length=64), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urls_original_url_hash'), ['original_url_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_urls_short_code'), ['short_code'], unique=True)

    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clicks_accessed_at'), ['accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clicks_url_id'), ['url_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clicks_url_id'))
        batch_op.drop_index(batch_op.f('ix_clicks_accessed_at'))

    op.drop_table('clicks')
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_short_code'))
        batch_op.drop_index(batch_op.f('ix_urls_original_url_hash'))

    op.drop_table('urls')
    # ### end Alembic commands ###
